services:
  - type: web
    name: book-search-engine-backend
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    branch: main
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET_KEY
        value: ${JWT_SECRET_KEY}
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com

  - type: web
    name: book-search-engine-frontend
    env: static
    buildCommand: npm run build --prefix client
    staticPublishPath: client/dist
    branch: main
