services:
  - type: web
    name: book-search-engine-backend
    env: node
    buildCommand: |
      NODE_ENV=development npm install
      npm run render-build
    startCommand: npm start
    branch: main
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://Thymezz:4Gh38fkcdFkKfU78@cluster0.mongodb.net/googlebooks?retryWrites=true&w=majority
      - key: JWT_SECRET_KEY
        value: q
      - key: NODE_ENV
        value: production

  - type: web
    name: book-search-engine-frontend
    env: static
    buildCommand: |
      NODE_ENV=development npm install --prefix client
      npm run build --prefix client
    staticPublishPath: client/dist
    branch: main
