services:
  - type: web
    name: book-search-engine-backend
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run render-build
    startCommand: npm start
    branch: main
    envVars:
      - key: MONGODB_URI
        value: ${mongodb+srv://Thymezz:4Gh38fkcdFkKfU78@cluster0.mongodb.net/googlebooks?retryWrites=true&w=majority}
      - key: JWT_SECRET_KEY
        value: ${q}


  - type: web
    name: book-search-engine-frontend
    env: static
    buildCommand: npm run build --prefix client
    staticPublishPath: client/dist
    branch: main
