services:
  - type: web
    name: book-search-engine-backend
    env: node
    buildCommand: |
      npm install --include=dev
      npm run build
      npm install --prefix client --legacy-peer-deps
      npm run build --prefix client
    startCommand: npm run start
    branch: main
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET_KEY
        value: ${JWT_SECRET_KEY}
      - key: NODE_ENV
        value: production

  - type: web
    name: book-search-engine-frontend
    env: static
    buildCommand: npm run build --prefix client
    staticPublishPath: client/dist
    branch: main
