services:
  - type: web
    name: book-search-engine-backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    branch: main
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET_KEY
        value: ${JWT_SECRET_KEY}
  - type: web
    name: book-search-engine-frontend
    env: static
    buildCommand: npm run build --prefix client
    staticPublishPath: client/dist
    branch: main
